version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_INITDB_ARGS='--locale=tr_TR.UTF-8'
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    links:
      - postgres

volumes:
  postgres_data:

networks:
  mynetwork:
